/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/ui/About.vue')['default']
    AdditionalInfo: typeof import('./src/components/ui/settings/AdditionalInfo.vue')['default']
    AvatarSelector: typeof import('./src/components/ui/auth/social/AvatarSelector.vue')['default']
    Can: typeof import('./src/components/landmarks/Can.vue')['default']
    CanUi: typeof import('./src/components/landmarks/CanUi.vue')['default']
    ChangelogMarkdown: typeof import('./src/components/ChangelogMarkdown.vue')['default']
    Contributing: typeof import('./src/components/ui/Contributing.vue')['default']
    Controls: typeof import('./src/components/ui/settings/tabs/Controls.vue')['default']
    CurrencyPanel: typeof import('./src/components/ui/auth/CurrencyPanel.vue')['default']
    CurrencyPanelItem: typeof import('./src/components/ui/auth/CurrencyPanelItem.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FriendLevelBar: typeof import('./src/components/ui/auth/social/FriendLevelBar.vue')['default']
    Friends: typeof import('./src/components/ui/auth/social/Friends.vue')['default']
    General: typeof import('./src/components/ui/settings/tabs/General.vue')['default']
    Graphics: typeof import('./src/components/ui/settings/tabs/Graphics.vue')['default']
    GridSlots: typeof import('./src/components/ui/inventory/GridSlots.vue')['default']
    InfinitePlane: typeof import('./src/components/InfinitePlane.vue')['default']
    Inventory: typeof import('./src/components/ui/inventory/Inventory.vue')['default']
    InventoryGrid: typeof import('./src/components/ui/inventory/InventoryGrid.vue')['default']
    InventoryItem: typeof import('./src/components/ui/inventory/InventoryItem.vue')['default']
    ItemIcon: typeof import('./src/components/ui/inventory/ItemIcon.vue')['default']
    ItemInfo: typeof import('./src/components/ui/inventory/ItemInfo.vue')['default']
    ItemInfoScreen: typeof import('./src/components/ui/inventory/ItemInfoScreen.vue')['default']
    LandmarkBuilder: typeof import('./src/components/landmarks/LandmarkBuilder.vue')['default']
    LandmarkImage: typeof import('./src/components/landmarks/LandmarkImage.vue')['default']
    LevelBar: typeof import('./src/components/ui/auth/LevelBar.vue')['default']
    MapCanvas: typeof import('./src/components/MapCanvas.vue')['default']
    MenuButton: typeof import('./src/components/ui/MenuButton.vue')['default']
    OrbitControls: typeof import('./src/components/player/OrbitControls.vue')['default']
    PlayerEntity: typeof import('./src/components/player/PlayerEntity.vue')['default']
    Profile: typeof import('./src/components/ui/auth/Profile.vue')['default']
    Requests: typeof import('./src/components/ui/auth/social/Requests.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenManager: typeof import('./src/components/ui/ScreenManager.vue')['default']
    Settings: typeof import('./src/components/ui/settings/Settings.vue')['default']
    ShapeVisualizer: typeof import('./src/components/ui/inventory/ShapeVisualizer.vue')['default']
    Social: typeof import('./src/components/ui/auth/social/Social.vue')['default']
    ToggleSwitch: typeof import('./src/components/ui/settings/ToggleSwitch.vue')['default']
    TrashCan: typeof import('./src/components/landmarks/TrashCan.vue')['default']
    TrashCans: typeof import('./src/components/landmarks/TrashCans.vue')['default']
    TrashCanUi: typeof import('./src/components/landmarks/TrashCanUi.vue')['default']
    UserAvatar: typeof import('./src/components/ui/auth/UserAvatar.vue')['default']
  }
}
