/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/ui/About.vue')['default']
    AdditionalInfo: typeof import('./src/components/ui/settings/AdditionalInfo.vue')['default']
    Altar: typeof import('./src/components/landmarks/Altar.vue')['default']
    Can: typeof import('./src/components/landmarks/Can.vue')['default']
    Cans: typeof import('./src/components/ui/contributing/Cans.vue')['default']
    Cardboard: typeof import('./src/components/ui/contributing/Cardboard.vue')['default']
    Contributing: typeof import('./src/components/ui/Contributing.vue')['default']
    Controls: typeof import('./src/components/ui/settings/tabs/Controls.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    General: typeof import('./src/components/ui/settings/tabs/General.vue')['default']
    Glass: typeof import('./src/components/ui/contributing/Glass.vue')['default']
    Graphics: typeof import('./src/components/ui/settings/tabs/Graphics.vue')['default']
    GridSlots: typeof import('./src/components/ui/inventory/GridSlots.vue')['default']
    Hero: typeof import('./src/components/home/Hero.vue')['default']
    InfinitePlane: typeof import('./src/components/InfinitePlane.vue')['default']
    Introduction: typeof import('./src/components/home/Introduction.vue')['default']
    Inventory: typeof import('./src/components/ui/inventory/Inventory.vue')['default']
    InventoryGrid: typeof import('./src/components/ui/inventory/InventoryGrid.vue')['default']
    InventoryItem: typeof import('./src/components/ui/inventory/InventoryItem.vue')['default']
    LandmarkImage: typeof import('./src/components/landmarks/LandmarkImage.vue')['default']
    LevelBar: typeof import('./src/components/ui/auth/LevelBar.vue')['default']
    Login: typeof import('./src/components/ui/auth/Login.vue')['default']
    MapCanvas: typeof import('./src/components/MapCanvas.vue')['default']
    Menu: typeof import('./src/components/ui/Menu.vue')['default']
    MenuButton: typeof import('./src/components/ui/MenuButton.vue')['default']
    OrbitControls: typeof import('./src/components/player/OrbitControls.vue')['default']
    Paper: typeof import('./src/components/ui/contributing/Cardboard.vue')['default']
    Plastic: typeof import('./src/components/ui/contributing/Plastic.vue')['default']
    PlayerEntity: typeof import('./src/components/player/PlayerEntity.vue')['default']
    Profile: typeof import('./src/components/ui/auth/Profile.vue')['default']
    ProfileDropdown: typeof import('./src/components/ui/auth/ProfileDropdown.vue')['default']
    Register: typeof import('./src/components/ui/auth/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/ui/settings/Settings.vue')['default']
    ToggleSwitch: typeof import('./src/components/ui/settings/ToggleSwitch.vue')['default']
    TopDownMapSection: typeof import('./src/components/ui/contributing/TopDownMapSection.vue')['default']
  }
}
